[env:espwatch-s3lg]
custom_meshtastic_hw_model = 141
custom_meshtastic_hw_model_slug = ESPWATCH_S3LG
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = ESPWATCH S3LG
custom_meshtastic_images = espwatch-s3lg.svg
custom_meshtastic_tags = Codesfish
custom_meshtastic_partition_scheme = 16MB

extends = esp32s3_base
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = espwatch-s3lg
board_check = true
board_build.partitions = default_16MB.csv
upload_protocol = esptool

build_unflags = -flto

lib_build_flags = -fno-lto

build_flags = ${esp32s3_base.build_flags}
  -fno-lto
  -Wl,-z,noexecstack
  -D ESPWATCH_S3LG
  -D BOARD_HAS_PSRAM
  ; -D MESHTASTIC_EXCLUDE_MQTT=1
  -D GNSS_MODEL_OVERRIDE=GNSS_MODEL_ATGM336H
  -D HAS_BUTTON=1
  -D I2C_SDA=1
  -D I2C_SCL=2
  -D PIN_BUZZER=3
  -D USE_PIN_BUZZER=PIN_BUZZER
  -D HAS_SCREEN=1
  -D HAS_TFT=1
  -D CONFIG_DISABLE_HAL_LOCKS=1
  -D USE_LOG_DEBUG
  -D LOG_DEBUG_INC=\"DebugConfiguration.h\"
  -D SPI_FREQUENCY=40000000
  -D SPI_READ_FREQUENCY=4000000
  -D TFT_HEIGHT=285
  -D TFT_WIDTH=240
  -D TFT_OFFSET_X=0
  -D TFT_OFFSET_Y=0
  -D TFT_OFFSET_ROTATION=0
  -D BRIGHTNESS_DEFAULT=13
  -Ivariants/esp32s3/espwatch-s3lg


build_src_filter = ${esp32s3_base.build_src_filter}

lib_deps = ${esp32s3_base.lib_deps}
  lewisxhe/SensorLib@0.3.4

lib_ignore = ${esp32_common.lib_ignore}
  Network

custom_sdkconfig =
  ${esp32s3_base.custom_sdkconfig}